return function(lnpm)
	lnpm.load('lumetas/lsyncer', function(lsyncer)
		lsyncer.setup()
		vim.api.nvim_set_keymap('n', '<leader>S', '', { noremap = true, desc = 'LSyncer' })
		vim.api.nvim_set_keymap('n', '<leader>Sc', ':LSyncer connect ', { noremap = true, desc = "LSyncer Connect" })
		vim.api.nvim_set_keymap('n', '<leader>Sl', ':LSyncer list<CR>', { noremap = true, desc = "LSyncer List" })
		vim.api.nvim_set_keymap('n', '<leader>Sp', ':LSyncer push<CR>', { noremap = true, desc = "LSyncer Push" })
		vim.api.nvim_set_keymap('n', '<leader>SP', ':LSyncer pull<CR>', { noremap = true, desc = "LSyncer Pull" })
		vim.api.nvim_set_keymap('n', '<leader>Ss', ':LSyncer sync<CR>', { noremap = true, desc = "LSyncer Sync" })
		vim.api.nvim_set_keymap('n', '<leader>Sd', ':LSyncer disconnect<CR>', { noremap = true, desc = "LSyncer Disconnect" })
		vim.api.nvim_set_keymap('n', '<leader>SC', ':LSyncer current<CR>', { noremap = true, desc = "LSyncer Current" })
		vim.api.nvim_set_keymap('n', '<leader>Sd', ':LSyncer delete<CR>', { noremap = true, desc = "LSyncer Delete" })
	end, {name = "lsyncer", lrule = function(next) vim.defer_fn(next, 100) end})
end
