return function(lnpm)
	local lrule = function(next)
		vim.keymap.set('n', '<leader>lp', function() next() vim.cmd('LumProjectsShow') end, { desc = 'Show projects' })
		vim.keymap.set('n', '<leader>lt', function() next() vim.cmd('LumProjectsTelescope') end, { desc = 'Show projects with telescope' })
		vim.keymap.set('n', '<leader>lr', function() next() vim.cmd('LumProjectsRun') end, { desc = 'Run project' })
		vim.keymap.set('n', '<leader>lb', function() next() vim.cmd('LumProjectsBuild') end, { desc = 'Build project' })
	end
	lnpm.load('lumetas/lum-projects.nvim', function(lumProjects)
		lumProjects.setup()
		vim.api.nvim_set_keymap('n', '<leader>lp', ':LumProjectsShow<CR>', { noremap = true, desc = 'Show projects' })
		vim.api.nvim_set_keymap('n', '<leader>lt', ':LumProjectsTelescope<CR>', { noremap = true, desc = 'Show projects with telescope' })
		vim.api.nvim_set_keymap('n', '<leader>lr', ':LumProjectsRun<CR>', { noremap = true, desc = 'Run project' })
		vim.api.nvim_set_keymap('n', '<leader>lb', ':LumProjectsBuild<CR>', { noremap = true, desc = 'Build project' })
	end, {name = 'lum-projects', lrule = lrule})
end
